# Generated by Django 3.2.2 on 2021-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Write your comment here...', max_length=1000, null=True, verbose_name='متن پيام'),
        ),
    ]
